-- Password here is placeholder hash generated by BCrypt for: Admin@12345
INSERT INTO AdminUsers (Username, PasswordHash, DisplayName)
VALUES ('admin', '$2a$11$hG5BfC5tw1m2WKsEByYQSuQf4r3o3f2W7/1vW6Cj8KfWgJ4z6b3nK', 'Default Administrator');

INSERT INTO SeoSettings (SiteName, DefaultTitle, DefaultDescription, DefaultKeywords, CanonicalBaseUrl)
VALUES ('MayaAstro', 'MayaAstro - Spiritual Insights', 'Professional astrology blogs, quotes and videos.',
        'astrology, blogs, quotes, youtube, seo', 'https://www.example.com');
